site_name: Risk of Bias
site_url: https://rob-luke.github.io/risk-of-bias
repo_url: https://github.com/rob-luke/risk-of-bias

theme:
  name: "material"

nav:
    - Home: index.md
    - Frameworks: frameworks.md
    - Command Line Interface: cli.md
    - API: api.md
    - Web: web.md
    - Contributing: contributing.md


markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.extra

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: numpy