from pathlib import Path

import matplotlib.figure

from risk_of_bias.compare import compare_frameworks
from risk_of_bias.frameworks.rob2 import get_rob2_framework
from risk_of_bias.types._response_types import ReasonedResponseWithEvidenceAndRawData
from risk_of_bias.visualisation import plot_assessor_agreement
